#日志的配置
log:
  log_file_name: logs_
  log_level: info
  log_format:  '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s]%(message)s'


database_config:
  host: shop-xo.hctestedu.com
  port: 3306
  database: shopxo_hctested
  user: api_test
  password: Aa9999!